// ? Window Object - The Window object offers various properties and methods 
// ?                 that enable interaction with the browser environment, including 
// ?                 manipulating the document, handling events, managing timers, 
// ?                 displaying dialog boxes, and more.
// ? The window object represents an open window in a browser. It is browser's object (not JavaScript's)
// ?  & is automatically created by browser.

